name: darin_flutter
description: Flutter inherited widget for Darin scopes.
version: 0.0.1
repository: https://github.com/TamasBarta/darin_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  darin: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

